# **Sử dụng Neural Network để xây dựng mô hình phân lớp trên bộ dữ liệu Iris từ thư viện sklearn (k-fold cross validation)**

In [1]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.preprocessing import MinMaxScaler

# a) Đọc bộ dữ liệu Iris từ sklearn
iris = load_iris()
X = iris.data
y = iris.target

# Display the first few rows of the data to understand its structure
df_iris = pd.DataFrame(data=X, columns=iris.feature_names)
df_iris['target'] = y
print("Original Iris dataset head:")
display(df_iris.head())


Original Iris dataset head:


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [2]:
# b) Chuẩn hóa dữ liệu data về đoạn [0,1]
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

# Display the scaled data
df_iris_scaled = pd.DataFrame(data=X_scaled, columns=iris.feature_names)
df_iris_scaled['target'] = y
print("Scaled Iris dataset head (features normalized to [0,1]):")
display(df_iris_scaled.head())


Scaled Iris dataset head (features normalized to [0,1]):


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0           0.222222          0.625000           0.067797          0.041667   
1           0.166667          0.416667           0.067797          0.041667   
2           0.111111          0.500000           0.050847          0.041667   
3           0.083333          0.458333           0.084746          0.041667   
4           0.194444          0.666667           0.067797          0.041667   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [5]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

def create_model(input_shape, num_classes):
    model = keras.Sequential([
        layers.Input(shape=input_shape),          # Input layer
        layers.Dense(10, activation='relu'),
        layers.Dense(8, activation='relu'),
        layers.Dense(num_classes, activation='softmax')
    ])

    model.compile(
        optimizer='adam',
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )

    return model


**d) Huấn luyện mô hình bằng k-fold cross validation (với k=10)**

In [9]:
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import numpy as np # Import numpy for calculating averages later

# Instantiate KFold with 10 splits, shuffling the data for better distribution,
# and a fixed random state for reproducibility.
kf = KFold(n_splits=10, shuffle=True, random_state=42)

# Initialize lists to store performance metrics for each fold
accuracies = []
precisions = []
recalss = [] # Renamed from 'recalls' to avoid potential conflict with built-in functions
f1_scores = []




**Train and Evaluate Model with K-Fold**

In [12]:
print("Huỳnh Thị Trúc Lam - 6351071040")
for fold, (train_index, test_index) in enumerate(kf.split(X_scaled, y)):
    print(f"\n--- Fold {fold+1}/{kf.n_splits} ---")

    # Split data into training and testing sets
    X_train, X_test = X_scaled[train_index], X_scaled[test_index]
    y_train, y_test = y[train_index], y[test_index]

    # Create a new model instance for each fold
    # Input shape is the number of features, num_classes is the number of unique target values
    model = create_model(input_shape=(X_scaled.shape[1],), num_classes=len(np.unique(y)))

    # Train the model
    # Set epochs to 50 and verbose to 0 to suppress output during training
    model.fit(X_train, y_train, epochs=50, verbose=0)

    # Make predictions on the test set
    y_pred_proba = model.predict(X_test)
    y_pred = np.argmax(y_pred_proba, axis=1)

    # Calculate metrics for the current fold
    fold_accuracy = accuracy_score(y_test, y_pred)
    fold_precision = precision_score(y_test, y_pred, average='weighted', zero_division=0)
    fold_recall = recall_score(y_test, y_pred, average='weighted', zero_division=0)
    fold_f1 = f1_score(y_test, y_pred, average='weighted', zero_division=0)

    # Print metrics for the current fold
    print(f"Accuracy: {fold_accuracy:.4f}")
    print(f"Precision: {fold_precision:.4f}")
    print(f"Recall: {fold_recall:.4f}")
    print(f"F1-Score: {fold_f1:.4f}")

    # Store metrics
    accuracies.append(fold_accuracy)
    precisions.append(fold_precision)
    recalss.append(fold_recall)
    f1_scores.append(fold_f1)

Huỳnh Thị Trúc Lam - 6351071040

--- Fold 1/10 ---
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step
Accuracy: 0.6000
Precision: 0.4667
Recall: 0.6000
F1-Score: 0.5000

--- Fold 2/10 ---
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step
Accuracy: 0.4667
Precision: 0.3212
Recall: 0.4667
F1-Score: 0.3524

--- Fold 3/10 ---
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step
Accuracy: 0.7333
Precision: 0.6444
Recall: 0.7333
F1-Score: 0.6667

--- Fold 4/10 ---
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step
Accuracy: 0.6667
Precision: 0.8333
Recall: 0.6667
F1-Score: 0.6032

--- Fold 5/10 ---
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step
Accuracy: 0.7333
Precision: 0.5852
Recall: 0.7333
F1-Score: 0.6381

--- Fold 6/10 ---
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step
Accuracy: 0.6000
Precision: 0.4667
Recall: 0.6000
F1-Score: 0.5000

--- Fold 7/10 ---
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step
Accuracy: 0.7333
Precision: 0.5444
Recall: 0.7333
F1-Score: 0.6230

--- Fold 8/10 ---
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step
Accuracy: 0.6000
Precision: 0.4000
Recall:

**e) In ra Average Accuracy, Average Recall, Average Precision, Average F1-score của mô hình sau quá trình huấn luyện với k-fold cross validation**

In [15]:
print("Huỳnh Thị Trúc Lam - 6351071040")
print(f"\n--- Average Metrics across {kf.n_splits} Folds ---")
print(f"Average Accuracy: {np.mean(accuracies):.4f}")
print(f"Average Precision: {np.mean(precisions):.4f}")
print(f"Average Recall: {np.mean(recalss):.4f}")
print(f"Average F1-Score: {np.mean(f1_scores):.4f}")

Huỳnh Thị Trúc Lam - 6351071040

--- Average Metrics across 10 Folds ---
Average Accuracy: 0.6800
Average Precision: 0.5832
Average Recall: 0.6800
Average F1-Score: 0.5929


**f) In ra Average Recall, Average Precision, Average F1-score cho từng class của mô hình sau quá trình huấn luyện với k-fold cross validation.**

In [22]:
print("Huỳnh Thị Trúc Lam - 6351071040")
# Convert lists of per-class metrics to NumPy arrays for easy averaging
# per_class_precisions will be a list of arrays, each array containing per-class precision for one fold.
# Stacking them will create a 2D array where rows are folds and columns are classes.
per_class_precisions_array = np.array(per_class_precisions)
per_class_recalls_array = np.array(per_class_recalls)
per_class_f1_scores_array = np.array(per_class_f1_scores)

# Calculate the average across all folds (axis=0) for each class
average_per_class_precision = np.mean(per_class_precisions_array, axis=0)
average_per_class_recall = np.mean(per_class_recalls_array, axis=0)
average_per_class_f1_score = np.mean(per_class_f1_scores_array, axis=0)

print("\n--- Average Per-Class Metrics across all Folds ---")
num_classes = len(average_per_class_precision)
for i in range(num_classes):
    print(f"Class {i}:")
    print(f"  Average Precision: {average_per_class_precision[i]:.4f}")
    print(f"  Average Recall: {average_per_class_recall[i]:.4f}")
    print(f"  Average F1-Score: {average_per_class_f1_score[i]:.4f}")

Huỳnh Thị Trúc Lam - 6351071040

--- Average Per-Class Metrics across all Folds ---
Class 0:
  Average Precision: 1.0000
  Average Recall: 1.0000
  Average F1-Score: 1.0000
Class 1:
  Average Precision: 0.6000
  Average Recall: 0.2650
  Average F1-Score: 0.3500
Class 2:
  Average Precision: 0.5783
  Average Recall: 1.0000
  Average F1-Score: 0.7223


**g) Sử dụng các mô hình phân lớp có F1-score tốt nhất đã huấn luyện ở trên cho 03 mẫu dữ liệu mới sau**

[6.2, 2.9, 4.3, 1.3]

[5.1, 3.5, 1.4, 0.2]

[7.3, 2.8, 6.4, 2.1]

In [24]:
import numpy as np

# 1. Define the three new data samples as a NumPy array
new_samples = np.array([
    [6.2, 2.9, 4.3, 1.3],
    [5.1, 3.5, 1.4, 0.2],
    [7.3, 2.8, 6.4, 2.1]
])

print("Original new samples:")
print(new_samples)

# 2. Scale the new_samples using the previously fitted scaler
new_samples_scaled = scaler.transform(new_samples)

print("\nScaled new samples:")
print(new_samples_scaled)

Original new samples:
[[6.2 2.9 4.3 1.3]
 [5.1 3.5 1.4 0.2]
 [7.3 2.8 6.4 2.1]]

Scaled new samples:
[[0.52777778 0.375      0.55932203 0.5       ]
 [0.22222222 0.625      0.06779661 0.04166667]
 [0.83333333 0.33333333 0.91525424 0.83333333]]


In [27]:
print("Huỳnh Thị Trúc Lam - 6351071040")
# Retrain a single model on the entire dataset
# Input shape is the number of features, num_classes is the number of unique target values
final_model = create_model(input_shape=(X_scaled.shape[1],), num_classes=len(np.unique(y)))

print("\nTraining final model on the entire dataset...")
# Train the model with 50 epochs
final_model.fit(X_scaled, y, epochs=50, verbose=0)
print("Final model trained successfully.")

Huỳnh Thị Trúc Lam - 6351071040

Training final model on the entire dataset...
Final model trained successfully.


In [29]:
print("Huỳnh Thị Trúc Lam - 6351071040")
# Make predictions on the scaled new samples
predictions_proba = final_model.predict(new_samples_scaled)
predicted_classes = np.argmax(predictions_proba, axis=1)

print("\nPredictions for new samples:")
for i, sample in enumerate(new_samples):
    print(f"Sample {i+1} ({sample}): Predicted class = {predicted_classes[i]} (Iris {iris.target_names[predicted_classes[i]]})")

Huỳnh Thị Trúc Lam - 6351071040
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step

Predictions for new samples:
Sample 1 ([6.2 2.9 4.3 1.3]): Predicted class = 1 (Iris versicolor)
Sample 2 ([5.1 3.5 1.4 0.2]): Predicted class = 0 (Iris setosa)
Sample 3 ([7.3 2.8 6.4 2.1]): Predicted class = 2 (Iris virginica)
